version: '3'

services:
  db:
    image: mongo:3.0.2
    ports:
        - "27017:27017"
  web:
    image: mutual-clouds
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
